### ISSUE TITLE
Lista de tareas de base de datos

### ISSUE THREAD

**Issue by Matias-Saig** [DS-The-Code-Team/proyecto-integrador#1]
**Lista de tareas Base de datos**

1. Definir entidades
2. Asignarle atributos
3. Determinar las pk y fk
4. Determinar relaciones
5. Normalizar
6. Hacer diagrama
7. Hacer documentación

**Comment by carolita-s** [comment]
Las entidades principales del sistema:
Empleados
Clientes
Acciones
Transacciones
los atributos para cada entidad:
Empleados:
ID_empleado (PK)
Nombre
Apellido
Cargo
Fecha de contratación
Clientes:
ID_cliente (PK)
Nombre
Apellido
Dirección
Teléfono
Email
Acciones:
ID_accion (PK)
Nombre
Precio
Cantidad_disponible
Transacciones:
ID_transaccion (PK)
ID_cliente (FK)
ID_accion (FK)
Tipo (compra/venta)
Cantidad
Fecha
Las relaciones entre las entidades identificadas:
Empleados y Clientes: Relación uno a muchos (Un empleado puede atender a varios clientes)
Clientes y Transacciones: Relación uno a muchos (Un cliente puede realizar varias transacciones)
Acciones y Transacciones: Relación uno a muchos (Una acción puede estar involucrada en varias transacciones)
