### ISSUE TITLE
Lista de tareas de programación

### ISSUE THREAD

**Issue by Matias-Saig** [DS-The-Code-Team/proyecto-integrador#2]
**Lista de tareas de programación**

1 - Identificar clases 
2 - Crear clases
3 - Establecer relaciones
4 - Realizar diagrama de clases
5 - Documentar diagrama

**Comment by Agus-lopez2022** [comment]
[clases.txt](https://github.com/user-attachments/files/15526621/clases.txt)

**Comment by Matias-Saig** [comment]
Diagrama de clase terminado
